server:
    port: 8888
spring:
    application:
        name: configuration-service
    cloud:
        config:
            server:
                bootstrap: true
                git:
                    uri: git@github.com:digitalcloudninja/application-default-config.git
                    default-label: master
        loadbalancer:
            enabled: false
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        region: us-east-1
        registry-fetch-interval-seconds: 30
        enabled: true
    instance:
        prefer-ip-address: true

